#!/bin/bash

version="trusty"

tmpdir=$(mktemp -d)

IMAGEDIR=$tmpdir/ubuntu/rootfs

wget https://partner-images.canonical.com/core/trusty/current/ubuntu-$version-core-cloudimg-amd64-root.tar.gz -O $tmpdir/root.tar.gz
mkdir -p $IMAGEDIR
pushd $IMAGEDIR
tar xf $tmpdir/root.tar.gz
popd

sudo cp base.sh $IMAGEDIR/script.sh
sudo systemd-nspawn -D $IMAGEDIR chmod +x /script.sh
sudo systemd-nspawn -D $IMAGEDIR /script.sh
sudo systemd-nspawn -D $IMAGEDIR rm -f /script.sh

# Build tar
pushd $IMAGEDIR
sudo tar Jcf $tmpdir/ubuntu.tar.xz .
popd

cp -p $tmpdir/ubuntu.tar.xz .

# Clean up
sudo rm -rf $tmpdir
